import { useState } from 'react';
import Head from 'next/head';

import DatePicker from '../components/DatePicker/DatePicker';
import Calendar from '../components/Calendar/Calendar';
import DateObject from 'react-date-object';

export default function Home() {
	// const [value, setValue] = useState({
	// 	startDate: new Date(),
	// 	endDate: new Date(),
	// });
	const [value, setValue] = useState([null, null]);

	const buttons = [
		'5 دقیقه اخیر',
		'15 دقیقه اخیر',
		'نیم ساعت اخیر',
		'یک ساعت اخیر',
		'دو ساعت اخیر',
		'یک روز اخیر',
		'بازه دلخواه',
	];

	return (
		<>
			<Head>
				<title>Range Date Picker Next Ts</title>
				<meta
					name='description'
					content='Range Date Picker Next Ts Generated by create next app'
				/>
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main
				dir='rtl'
				className='bg- flex h-screen w-full flex-col items-center justify-center font-iranyekan'>
				<section className='rounded-xl bg-white px-6 py-2'>
					<DatePicker
						value={value}
						onChange={setValue}
						maxDate={new Date()}
						calendarStyle='w-auto h-auto flex justify-between items-center rounded-md text-center'
						allDayStyles='w-12 h-12 flex justify-center items-center cursor-pointer text-black'
						todayStyle='text-primary'
						oneDaySelectStyle='text-black bg- rounde '
						rangeDateStyle='bg-sky-200'
						startRangeDayStyle='bg-primary text- rounded-r-md'
						// startRangeDayStyle='rounded-r-md'
						endRangeDayStyle='bg-primary '
						calendar={undefined}
						customWeekDays={[]}
						weekStartDayIndex={0}
						// eslint-disable-next-line react/no-children-prop
						children={undefined}
						minDate={undefined}
						disableMonthPicker={undefined}
						onFocusedDateChange={function (a: any) {
							throw new Error('Function not implemented.');
						}}
						className={''}
						selectedDayStyle={''}
						ref={undefined} // endRangeDayStyle='rounded-l-md'
						onReady={function () {
							throw new Error('Function not implemented.');
						}} // endRangeDayStyle='bg-primary'
						name={''}
						required={false}
						inputClass={''}
						disabled={false}
						render={undefined}
						weekDays={[]}
						months={[]}
						inputMode={undefined}
						hideOnScroll={false}
						containerClassName={''}
						calendarPosition={''}
						editable={false}
						onOpen={function () {
							throw new Error('Function not implemented.');
						}}
						onClose={function () {
							throw new Error('Function not implemented.');
						}}
						zIndex={0}
						arrow={false}
						fixMainPosition={undefined}
						onPropsChange={undefined}
						digits={undefined}
						type={undefined}
						onOpenPickNewDate={false}
						inputLabel={''}
						inputLabelClassname={''}
						inputClassname={''}
						format={''}
					/>
				</section>
			</main>
		</>
	);
}
